name: uv.lock check

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"

jobs:
  uv-lock-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: hbelmiro/uv-lock-check@814bb91b9521353fce69abced9210c8b42467d6d  # v0.2.0
        with:
          command: "uv lock --check"
